service: layer-nodejs-modules

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
    layers:
      - {Ref: NodeModulesLambdaLayer}

layers:
  NodeModules:
    path: layer
    compatibleRuntimes:
      - nodejs12.x